Update github-action.yml

diff --git a/.github/workflows/github-action.yml b/.github/workflows/github-action.yml
--- a/.github/workflows/github-action.yml
+++ b/.github/workflows/github-action.yml
@@ -33,7 +33,7 @@ jobs:
           WS_USERKEY: ${{secrets.USERKEY}}
           WS_WSS_URL: https://app.whitesourcesoftware.com/agent
           WS_PRODUCTNAME: GH_${{github.event.repository.name}}
-          WS_PROJECTNAME: ${{github.ref}}_Prioritize
+          WS_PROJECTNAME: ${{github.ref}}_Prioritize-1.5
           WS_ENABLEIMPACTANALYSIS: true
           WS_REQUIREKNOWNSHA1: false
           WS_RESOLVEALLDEPENDENCIES: false
@@ -47,3 +47,44 @@ jobs:
           WARFILE=$(find ./ -type f -wholename "*/target/*.war")
           echo $WARFILE will be added to appPath
           java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
+          
+      - name: Generate WhiteSource SPDX Report
+        env:
+          WS_WSS_URL: https://app.whitesourcesoftware.com/agent
+        run: |
+            export WS_PROJECTTOKEN=$(jq -r '.projects | .[] | .projectToken' ./whitesource/scanProjectDetails.json)
+            echo WS_PROJECTTOKEN: $WS_PROJECTTOKEN
+            export WS_URL=$(echo $WS_WSS_URL | awk -F "agent" '{print $1}')
+            echo WS_URL: $WS_URL
+            echo === Installing WhiteSource SBOM Generator ===
+            pip  install ws_sbom_generator
+            echo === Checking Project State before generating SBOM ===
+            IFS="|"
+            scan_status=true
+            pass_status=("UPDATE"${IFS}"FINISH"${IFS}"DIFF")
+            fail_status=("UNKNOWN"${IFS}"FAIL")
+            while $scan_status
+            do
+              new_status=$(curl -s -X POST -H "Content-Type: application/json" -d '{"requestType":"getProjectState", "userKey": "'$WS_USERKEY'", "projectToken":"'$WS_PROJECTTOKEN'"}' $WS_URL/api/v1.3 | jq '.projectState|.lastProcess' | tr -d '"')
+              if [[ "${IFS}${pass_status[*]}${IFS}" =~ "${IFS}${new_status}${IFS}" ]];
+              then
+                      scan_status=false
+                      echo "Project information has been uploaded successfully!"
+              else
+                      echo "Scan is still processing..."
+                      sleep 10
+              fi
+              if [[ "${IFS}${fail_status[*]}${IFS}" =~ "${IFS}${new_status}${IFS}" ]];
+              then
+                      echo "Scan failed to upload...exiting program"
+                      exit 1
+              fi
+            done
+            unset IFS
+            echo === Generating SBOM ===
+            ws_sbom_generator -u ${{secrets.USERKEY}} -k ${{secrets.APIKEY}} -s $WS_PROJECTTOKEN -a $WS_URL -t tv -o ./whitesource-spdx
+      - name: Publish WhiteSource SPDX Report
+        uses: actions/upload-artifact@master
+        with:
+           name: WhiteSource SPDX report
+           path: ${{github.workspace}}/whitesource-spdx
